"""add_company_members_table

Revision ID: 47b5eed6692b
Revises: f1e2d3c4b5a6
Create Date: 2026-03-16 18:28:58.540679

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47b5eed6692b'
down_revision = 'f1e2d3c4b5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('invited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_id', name='uq_company_member')
    )
    op.drop_table('candidate_skills')
    op.drop_index('ix_assessment_reports_candidate_id', table_name='assessment_reports')
    op.drop_index('ix_candidates_user_id', table_name='candidates')
    op.drop_index('ix_companies_owner_user_id', table_name='companies')
    op.drop_index('ix_interview_messages_interview_id', table_name='interview_messages')
    op.drop_index('ix_interviews_candidate_id', table_name='interviews')
    op.drop_index('ix_interviews_status', table_name='interviews')
    op.drop_index('ix_resumes_candidate_id', table_name='resumes')
    op.drop_index('ix_users_email', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_resumes_candidate_id', 'resumes', ['candidate_id'], unique=False)
    op.create_index('ix_interviews_status', 'interviews', ['status'], unique=False)
    op.create_index('ix_interviews_candidate_id', 'interviews', ['candidate_id'], unique=False)
    op.create_index('ix_interview_messages_interview_id', 'interview_messages', ['interview_id'], unique=False)
    op.create_index('ix_companies_owner_user_id', 'companies', ['owner_user_id'], unique=False)
    op.create_index('ix_candidates_user_id', 'candidates', ['user_id'], unique=False)
    op.create_index('ix_assessment_reports_candidate_id', 'assessment_reports', ['candidate_id'], unique=False)
    op.create_table('candidate_skills',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('proficiency', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('evidence_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name='candidate_skills_candidate_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['assessment_reports.id'], name='candidate_skills_report_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='candidate_skills_pkey')
    )
    op.drop_table('company_members')
    # ### end Alembic commands ###
