"""add assessment report confidence fields

Revision ID: 710ec267d0b1
Revises: 968fa1a296c4
Create Date: 2026-03-19 10:19:01.681640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '710ec267d0b1'
down_revision = '968fa1a296c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_reports', sa.Column('overall_confidence', sa.Float(), nullable=True))
    op.add_column('assessment_reports', sa.Column('competency_confidence', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('assessment_reports', sa.Column('confidence_reasons', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('assessment_reports', sa.Column('evidence_coverage', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('assessment_reports', sa.Column('decision_policy_version', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_reports', 'decision_policy_version')
    op.drop_column('assessment_reports', 'evidence_coverage')
    op.drop_column('assessment_reports', 'confidence_reasons')
    op.drop_column('assessment_reports', 'competency_confidence')
    op.drop_column('assessment_reports', 'overall_confidence')
    # ### end Alembic commands ###
