"""add_company_assessments

Revision ID: bc183245d27d
Revises: 47b5eed6692b
Create Date: 2026-03-16 18:40:48.753679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc183245d27d'
down_revision = '47b5eed6692b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('employee_email', sa.String(length=255), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.add_column('interviews', sa.Column('company_assessment_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'interviews', 'company_assessments', ['company_assessment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'company_assessment_id')
    op.drop_table('company_assessments')
    # ### end Alembic commands ###
