"""add_followup_depth_to_interviews

Revision ID: ea2b4855e5b5
Revises: 710ec267d0b1
Create Date: 2026-03-30 10:05:28.210712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2b4855e5b5'
down_revision = '710ec267d0b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('followup_depth', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'followup_depth')
    # ### end Alembic commands ###
