"""add_interview_state_json

Revision ID: f1936ae5a32d
Revises: ea2b4855e5b5
Create Date: 2026-03-30 10:19:42.207977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1936ae5a32d'
down_revision = 'ea2b4855e5b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('interview_state', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'interview_state')
    # ### end Alembic commands ###
