"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { useAuth } from "@/hooks/useAuth";
import { reportApi } from "@/lib/api";
import type { AssessmentReport, HiringRecommendation } from "@/lib/types";

const RECOMMENDATION_CONFIG: Record<
  HiringRecommendation,
  { label: string; color: string; bg: string }
> = {
  strong_yes: { label: "Strong Yes", color: "text-green-400", bg: "bg-green-500/10 border-green-500/30" },
  yes: { label: "Yes", color: "text-blue-400", bg: "bg-blue-500/10 border-blue-500/30" },
  maybe: { label: "Maybe", color: "text-yellow-400", bg: "bg-yellow-500/10 border-yellow-500/30" },
  no: { label: "No", color: "text-red-400", bg: "bg-red-500/10 border-red-500/30" },
};

export default function ReportPage() {
  const { id } = useParams<{ id: string }>();
  const { loading: authLoading } = useAuth();
  const [report, setReport] = useState<AssessmentReport | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!id || authLoading) return;
    reportApi.getById(id).catch(() => setError("Could not load report"));
    // Temporary: fetch via interview detail until report endpoint is wired
    // For now use interviewApi.getDetail approach — reportApi.getById will work in Phase 5
    reportApi
      .getById(id)
      .then(setReport)
      .catch(() => setError("Could not load report"));
  }, [id, authLoading]);

  if (authLoading || (!report && !error)) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center">
        <div className="text-slate-400">{error || "Loading report…"}</div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen bg-slate-900 flex items-center justify-center px-4">
        <div className="text-center">
          <div className="text-red-400 mb-4">{error}</div>
          <Link href="/candidate/dashboard" className="text-blue-400 hover:underline text-sm">
            ← Back to dashboard
          </Link>
        </div>
      </div>
    );
  }

  const rec = RECOMMENDATION_CONFIG[report.hiring_recommendation];

  return (
    <div className="min-h-screen bg-slate-900 px-4 py-10">
      <div className="max-w-2xl mx-auto">
        <Link href="/candidate/dashboard" className="text-slate-400 hover:text-white text-sm mb-6 inline-block">
          ← Back to dashboard
        </Link>

        <h1 className="text-2xl font-bold text-white mb-2">Assessment Report</h1>

        {report.interview_summary && (
          <p className="text-slate-400 mb-8">{report.interview_summary}</p>
        )}

        {/* Recommendation badge */}
        <div className={`inline-flex items-center gap-2 border rounded-full px-4 py-1.5 text-sm font-semibold mb-8 ${rec.bg} ${rec.color}`}>
          Hiring Recommendation: {rec.label}
        </div>

        {/* Score cards */}
        <div className="grid grid-cols-2 gap-4 mb-8">
          <ScoreCard label="Overall Score" score={report.overall_score} highlight />
          <ScoreCard label="Hard Skills" score={report.hard_skills_score} />
          <ScoreCard label="Soft Skills" score={report.soft_skills_score} />
          <ScoreCard label="Communication" score={report.communication_score} />
        </div>

        {/* Strengths */}
        {report.strengths.length > 0 && (
          <Section title="Strengths" color="green">
            {report.strengths.map((s, i) => (
              <ListItem key={i} text={s} bullet="✓" color="text-green-400" />
            ))}
          </Section>
        )}

        {/* Weaknesses */}
        {report.weaknesses.length > 0 && (
          <Section title="Areas to Improve" color="yellow">
            {report.weaknesses.map((w, i) => (
              <ListItem key={i} text={w} bullet="△" color="text-yellow-400" />
            ))}
          </Section>
        )}

        {/* Recommendations */}
        {report.recommendations.length > 0 && (
          <Section title="Recommendations" color="blue">
            {report.recommendations.map((r, i) => (
              <ListItem key={i} text={r} bullet="→" color="text-blue-400" />
            ))}
          </Section>
        )}

        <div className="text-slate-600 text-xs mt-8">
          Generated by model {report.model_version} · {new Date(report.created_at).toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}

function ScoreCard({ label, score, highlight = false }: { label: string; score: number | null; highlight?: boolean }) {
  const value = score ?? 0;
  const pct = (value / 10) * 100;
  return (
    <div className={`bg-slate-800 border rounded-xl p-5 ${highlight ? "border-blue-500/40" : "border-slate-700"}`}>
      <div className="text-slate-400 text-sm mb-2">{label}</div>
      <div className={`text-3xl font-bold mb-3 ${highlight ? "text-blue-400" : "text-white"}`}>
        {value.toFixed(1)}
        <span className="text-slate-500 text-lg font-normal">/10</span>
      </div>
      <div className="h-1.5 bg-slate-700 rounded-full overflow-hidden">
        <div
          className={`h-full rounded-full transition-all ${highlight ? "bg-blue-500" : "bg-slate-400"}`}
          style={{ width: `${pct}%` }}
        />
      </div>
    </div>
  );
}

function Section({ title, children, color }: { title: string; children: React.ReactNode; color: string }) {
  const colors: Record<string, string> = {
    green: "text-green-400",
    yellow: "text-yellow-400",
    blue: "text-blue-400",
  };
  return (
    <div className="bg-slate-800 border border-slate-700 rounded-xl p-6 mb-4">
      <h2 className={`font-semibold mb-3 ${colors[color] ?? "text-white"}`}>{title}</h2>
      <ul className="space-y-2">{children}</ul>
    </div>
  );
}

function ListItem({ text, bullet, color }: { text: string; bullet: string; color: string }) {
  return (
    <li className="flex gap-3 text-sm text-slate-300">
      <span className={`${color} shrink-0 mt-0.5`}>{bullet}</span>
      {text}
    </li>
  );
}
